/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SelectCompanyRouteImport } from './routes/select-company'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CriarEmpresaRouteImport } from './routes/criar-empresa'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AdicionarClinicaRouteImport } from './routes/adicionar-clinica'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CadastroTokenRouteImport } from './routes/cadastro.$token'
import { Route as AssinarTermoUuidRouteImport } from './routes/assinar-termo.$uuid'
import { Route as AssinarContratoUuidRouteImport } from './routes/assinar-contrato.$uuid'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedProntuarioRouteImport } from './routes/_authenticated/prontuario'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedLixeiraRouteImport } from './routes/_authenticated/lixeira'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTermosIndexRouteImport } from './routes/_authenticated/termos/index'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated/contratos/index'
import { Route as AuthenticatedTermosIdRouteImport } from './routes/_authenticated/termos/$id'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated/contratos/$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectCompanyRoute = SelectCompanyRouteImport.update({
  id: '/select-company',
  path: '/select-company',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarEmpresaRoute = CriarEmpresaRouteImport.update({
  id: '/criar-empresa',
  path: '/criar-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarClinicaRoute = AdicionarClinicaRouteImport.update({
  id: '/adicionar-clinica',
  path: '/adicionar-clinica',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CadastroTokenRoute = CadastroTokenRouteImport.update({
  id: '/cadastro/$token',
  path: '/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarTermoUuidRoute = AssinarTermoUuidRouteImport.update({
  id: '/assinar-termo/$uuid',
  path: '/assinar-termo/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarContratoUuidRoute = AssinarContratoUuidRouteImport.update({
  id: '/assinar-contrato/$uuid',
  path: '/assinar-contrato/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProntuarioRoute = AuthenticatedProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLixeiraRoute = AuthenticatedLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTermosIndexRoute =
  AuthenticatedTermosIndexRouteImport.update({
    id: '/termos/',
    path: '/termos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTermosIdRoute = AuthenticatedTermosIdRouteImport.update({
  id: '/termos/$id',
  path: '/termos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/contratos/$id',
    path: '/contratos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/adicionar-clinica': typeof AdicionarClinicaRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/criar-empresa': typeof CriarEmpresaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-company': typeof SelectCompanyRoute
  '/test': typeof TestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/assinar-contrato/$uuid': typeof AssinarContratoUuidRoute
  '/assinar-termo/$uuid': typeof AssinarTermoUuidRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/termos/$id': typeof AuthenticatedTermosIdRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/termos/': typeof AuthenticatedTermosIndexRoute
}
export interface FileRoutesByTo {
  '/aceitar-convite': typeof AceitarConviteRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/adicionar-clinica': typeof AdicionarClinicaRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/criar-empresa': typeof CriarEmpresaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-company': typeof SelectCompanyRoute
  '/test': typeof TestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/assinar-contrato/$uuid': typeof AssinarContratoUuidRoute
  '/assinar-termo/$uuid': typeof AssinarTermoUuidRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/termos/$id': typeof AuthenticatedTermosIdRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/termos': typeof AuthenticatedTermosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/adicionar-clinica': typeof AdicionarClinicaRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/criar-empresa': typeof CriarEmpresaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-company': typeof SelectCompanyRoute
  '/test': typeof TestRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/lixeira': typeof AuthenticatedLixeiraRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/prontuario': typeof AuthenticatedProntuarioRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/assinar-contrato/$uuid': typeof AssinarContratoUuidRoute
  '/assinar-termo/$uuid': typeof AssinarTermoUuidRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/_authenticated/termos/$id': typeof AuthenticatedTermosIdRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/_authenticated/termos/': typeof AuthenticatedTermosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/acesso-negado'
    | '/adicionar-clinica'
    | '/aguardando-aprovacao'
    | '/criar-empresa'
    | '/login'
    | '/reset-password'
    | '/select-company'
    | '/test'
    | '/admin'
    | '/lixeira'
    | '/perfil'
    | '/prontuario'
    | '/suporte'
    | '/usuarios'
    | '/assinar-contrato/$uuid'
    | '/assinar-termo/$uuid'
    | '/cadastro/$token'
    | '/contratos/$id'
    | '/termos/$id'
    | '/contratos/'
    | '/termos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aceitar-convite'
    | '/acesso-negado'
    | '/adicionar-clinica'
    | '/aguardando-aprovacao'
    | '/criar-empresa'
    | '/login'
    | '/reset-password'
    | '/select-company'
    | '/test'
    | '/admin'
    | '/lixeira'
    | '/perfil'
    | '/prontuario'
    | '/suporte'
    | '/usuarios'
    | '/assinar-contrato/$uuid'
    | '/assinar-termo/$uuid'
    | '/cadastro/$token'
    | '/'
    | '/contratos/$id'
    | '/termos/$id'
    | '/contratos'
    | '/termos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/aceitar-convite'
    | '/acesso-negado'
    | '/adicionar-clinica'
    | '/aguardando-aprovacao'
    | '/criar-empresa'
    | '/login'
    | '/reset-password'
    | '/select-company'
    | '/test'
    | '/_authenticated/admin'
    | '/_authenticated/lixeira'
    | '/_authenticated/perfil'
    | '/_authenticated/prontuario'
    | '/_authenticated/suporte'
    | '/_authenticated/usuarios'
    | '/assinar-contrato/$uuid'
    | '/assinar-termo/$uuid'
    | '/cadastro/$token'
    | '/_authenticated/'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/termos/$id'
    | '/_authenticated/contratos/'
    | '/_authenticated/termos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AdicionarClinicaRoute: typeof AdicionarClinicaRoute
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  CriarEmpresaRoute: typeof CriarEmpresaRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectCompanyRoute: typeof SelectCompanyRoute
  TestRoute: typeof TestRoute
  AssinarContratoUuidRoute: typeof AssinarContratoUuidRoute
  AssinarTermoUuidRoute: typeof AssinarTermoUuidRoute
  CadastroTokenRoute: typeof CadastroTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-company': {
      id: '/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof SelectCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-empresa': {
      id: '/criar-empresa'
      path: '/criar-empresa'
      fullPath: '/criar-empresa'
      preLoaderRoute: typeof CriarEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar-clinica': {
      id: '/adicionar-clinica'
      path: '/adicionar-clinica'
      fullPath: '/adicionar-clinica'
      preLoaderRoute: typeof AdicionarClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/cadastro/$token': {
      id: '/cadastro/$token'
      path: '/cadastro/$token'
      fullPath: '/cadastro/$token'
      preLoaderRoute: typeof CadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar-termo/$uuid': {
      id: '/assinar-termo/$uuid'
      path: '/assinar-termo/$uuid'
      fullPath: '/assinar-termo/$uuid'
      preLoaderRoute: typeof AssinarTermoUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar-contrato/$uuid': {
      id: '/assinar-contrato/$uuid'
      path: '/assinar-contrato/$uuid'
      fullPath: '/assinar-contrato/$uuid'
      preLoaderRoute: typeof AssinarContratoUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prontuario': {
      id: '/_authenticated/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof AuthenticatedProntuarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lixeira': {
      id: '/_authenticated/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedLixeiraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/termos/': {
      id: '/_authenticated/termos/'
      path: '/termos'
      fullPath: '/termos/'
      preLoaderRoute: typeof AuthenticatedTermosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/termos/$id': {
      id: '/_authenticated/termos/$id'
      path: '/termos/$id'
      fullPath: '/termos/$id'
      preLoaderRoute: typeof AuthenticatedTermosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLixeiraRoute: typeof AuthenticatedLixeiraRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProntuarioRoute: typeof AuthenticatedProntuarioRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRoute
  AuthenticatedTermosIdRoute: typeof AuthenticatedTermosIdRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
  AuthenticatedTermosIndexRoute: typeof AuthenticatedTermosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLixeiraRoute: AuthenticatedLixeiraRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProntuarioRoute: AuthenticatedProntuarioRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContratosIdRoute: AuthenticatedContratosIdRoute,
  AuthenticatedTermosIdRoute: AuthenticatedTermosIdRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  AuthenticatedTermosIndexRoute: AuthenticatedTermosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AdicionarClinicaRoute: AdicionarClinicaRoute,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  CriarEmpresaRoute: CriarEmpresaRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectCompanyRoute: SelectCompanyRoute,
  TestRoute: TestRoute,
  AssinarContratoUuidRoute: AssinarContratoUuidRoute,
  AssinarTermoUuidRoute: AssinarTermoUuidRoute,
  CadastroTokenRoute: CadastroTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
