/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CriarEmpresaRouteImport } from './routes/criar-empresa'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CadastroTokenRouteImport } from './routes/cadastro.$token'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedProntuarioRouteImport } from './routes/_authenticated/prontuario'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedLixeiraRouteImport } from './routes/_authenticated/lixeira'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultasRouteImport } from './routes/_authenticated/consultas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardLogsRouteImport } from './routes/_authenticated/dashboard_.logs'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin_.logs'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin_.dashboard'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarEmpresaRoute = CriarEmpresaRouteImport.update({
  id: '/criar-empresa',
  path: '/criar-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CadastroTokenRoute = CadastroTokenRouteImport.update({
  id: '/cadastro/$token',
  path: '/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProntuarioRoute = AuthenticatedProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLixeiraRoute = AuthenticatedLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsultasRoute = AuthenticatedConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardLogsRoute =
  AuthenticatedDashboardLogsRouteImport.update({
    id: '/dashboard_/logs',
    path: '/dashboard/logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin_/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin_/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/criar-empresa': typeof CriarEmpresaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test': typeof TestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/consultas': typeof AuthenticatedConsultasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
}
export interface FileRoutesByTo {
  '/aceitar-convite': typeof AceitarConviteRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/criar-empresa': typeof CriarEmpresaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test': typeof TestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/consultas': typeof AuthenticatedConsultasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/criar-empresa': typeof CriarEmpresaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test': typeof TestRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/consultas': typeof AuthenticatedConsultasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lixeira': typeof AuthenticatedLixeiraRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/prontuario': typeof AuthenticatedProntuarioRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin_/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin_/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/dashboard_/logs': typeof AuthenticatedDashboardLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/acesso-negado'
    | '/aguardando-aprovacao'
    | '/criar-empresa'
    | '/login'
    | '/reset-password'
    | '/test'
    | '/admin'
    | '/consultas'
    | '/dashboard'
    | '/lixeira'
    | '/perfil'
    | '/prontuario'
    | '/suporte'
    | '/usuarios'
    | '/cadastro/$token'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/dashboard/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aceitar-convite'
    | '/acesso-negado'
    | '/aguardando-aprovacao'
    | '/criar-empresa'
    | '/login'
    | '/reset-password'
    | '/test'
    | '/admin'
    | '/consultas'
    | '/dashboard'
    | '/lixeira'
    | '/perfil'
    | '/prontuario'
    | '/suporte'
    | '/usuarios'
    | '/cadastro/$token'
    | '/'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/dashboard/logs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/aceitar-convite'
    | '/acesso-negado'
    | '/aguardando-aprovacao'
    | '/criar-empresa'
    | '/login'
    | '/reset-password'
    | '/test'
    | '/_authenticated/admin'
    | '/_authenticated/consultas'
    | '/_authenticated/dashboard'
    | '/_authenticated/lixeira'
    | '/_authenticated/perfil'
    | '/_authenticated/prontuario'
    | '/_authenticated/suporte'
    | '/_authenticated/usuarios'
    | '/cadastro/$token'
    | '/_authenticated/'
    | '/_authenticated/admin_/dashboard'
    | '/_authenticated/admin_/logs'
    | '/_authenticated/dashboard_/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  CriarEmpresaRoute: typeof CriarEmpresaRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TestRoute: typeof TestRoute
  CadastroTokenRoute: typeof CadastroTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-empresa': {
      id: '/criar-empresa'
      path: '/criar-empresa'
      fullPath: '/criar-empresa'
      preLoaderRoute: typeof CriarEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/cadastro/$token': {
      id: '/cadastro/$token'
      path: '/cadastro/$token'
      fullPath: '/cadastro/$token'
      preLoaderRoute: typeof CadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prontuario': {
      id: '/_authenticated/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof AuthenticatedProntuarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lixeira': {
      id: '/_authenticated/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedLixeiraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consultas': {
      id: '/_authenticated/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof AuthenticatedConsultasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard_/logs': {
      id: '/_authenticated/dashboard_/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof AuthenticatedDashboardLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/logs': {
      id: '/_authenticated/admin_/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/dashboard': {
      id: '/_authenticated/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConsultasRoute: typeof AuthenticatedConsultasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLixeiraRoute: typeof AuthenticatedLixeiraRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProntuarioRoute: typeof AuthenticatedProntuarioRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedDashboardLogsRoute: typeof AuthenticatedDashboardLogsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConsultasRoute: AuthenticatedConsultasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLixeiraRoute: AuthenticatedLixeiraRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProntuarioRoute: AuthenticatedProntuarioRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedDashboardLogsRoute: AuthenticatedDashboardLogsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  CriarEmpresaRoute: CriarEmpresaRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TestRoute: TestRoute,
  CadastroTokenRoute: CadastroTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
